# Generated by Django 6.0.4 on 2026-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'I want to order food'), ('owner', 'I run a campus outlet')], default='customer', max_length=20),
        ),
    ]
