# Generated by Django 6.0.4 on 2026-04-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_covers/'),
        ),
    ]
