# Generated by Django 6.0.4 on 2026-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Waiting for payment'), ('placed', 'Order received'), ('confirmed', 'Confirmed by kitchen'), ('preparing', 'Being prepared'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered — enjoy!'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=30),
        ),
    ]
